<?php

$color_schemes=[
    'default' => [
      'title' => t('Default'),
      'colors' => [
      'Primary Color' => '#1b1c21',
      'Secondary Color' => '#5e5e5e',
      ],
    ],
    'set_1' => [
      'title' => t('Color Set 1'),
      'colors' => [
      'Primary Color' => '#d2a679',
      'Secondary Color' => '#014b5f',
      ],
    ],
    'set_2' => [
      'title' => t('Color Set 2'),
      'colors' => [
      'Primary Color' => '#44bcc5',
      'Secondary Color' => '#153156',
      ],
    ],
    'set_3' => [
      'title' => t('Color Set 3'),
      'colors' => [
      'Primary Color' => '#cd6767',
      'Secondary Color' => '#282828',
      ],
    ],
    'set_4' => [
      'title' => t('Color Set 4'),
      'colors' => [
      'Primary Color' => '#d315a3',
      'Secondary Color' => '#153156',
      ],
    ],
    'set_5' => [
      'title' => t('Color Set 5'),
      'colors' => [
      'Primary Color' => '#608735',
      'Secondary Color' => '#000000',
      ],
    ],
    'set_6' => [
      'title' => t('Color Set 6'),
      'colors' => [
      'Primary Color' => '#c98723',
      'Secondary Color' => '#041b45',
      ],
    ],
    'set_7' => [
      'title' => t('Color Set 7'),
      'colors' => [
      'Primary Color' => '#f44336',
      'Secondary Color' => '#000000',
      ],
    ],
    'set_8' => [
      'title' => t('Color Set 8'),
      'colors' => [
      'Primary Color' => '#fB6a4f',
      'Secondary Color' => '#014b5f',
      ],
    ],
    'set_9' => [
      'title' => t('Color Set 9'),
      'colors' => [
      'Primary Color' => '#12b6b6',
      'Secondary Color' => '#000000',
      ],
    ],
];